# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('post', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_modfied', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
